package ZTI.projekt.model;

import com.fasterxml.jackson.annotation.JsonIgnore;
import jakarta.persistence.*;
import lombok.Data;


import java.util.Set;

/**
 * Entity representing an Exercise in the system.
 * This class is used as a model for the Exercise table in the database.
 * Lombok's @Data annotation is used for automatic generation of getters, setters, equals, hashCode and toString methods.
 */
@Entity
@Table(name = "exercises")
@Data
public class Exercise {

    /**
     * Unique identifier for the Exercise.
     * The value is automatically generated by the database.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long exercise_id;

    /**
     * Name of the Exercise.
     */
    private String name;

    /**
     * Number of sets in the Exercise.
     */
    private Integer sets;

    /**
     * Repetition range of the Exercise, represented as a String.
     */
    private String rep_range;

    /**
     * Set of TrainingSession entities in which the Exercise is included.
     * This field is ignored in JSON serialization and deserialization.
     */
    @ManyToMany(mappedBy = "exercises")
    @JsonIgnore
    private Set<TrainingSession> trainingSessions;
}
