package ZTI.projekt.model;

import jakarta.persistence.*;
import lombok.Getter;
import lombok.Setter;

import java.util.Date;
import java.util.Set;


/**
 * Entity representing a Training Session in the system.
 * This class is used as a model for the TrainingSession table in the database.
 * Lombok's @Getter and @Setter annotations are used for automatic generation of getters and setters.
 */
@Entity
@Table(name = "trainingsession")
@Getter
@Setter
public class TrainingSession {

    /**
     * Unique identifier for the TrainingSession.
     * The value is automatically generated by the database.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long training_id;

    /**
     * Name of the TrainingSession.
     */
    private String name;

    /**
     * Date of the TrainingSession.
     */
    private Date date;

    /**
     * Boolean field that indicates if the TrainingSession is completed.
     * By default, it is set to false in the database.
     */
    @Column(nullable = false, columnDefinition = "boolean default false")
    private boolean completed;

    /**
     * Set of Exercise entities associated with the TrainingSession.
     * This field establishes a many-to-many relationship with the Exercise entity,
     * and a join table is used to manage the relationship.
     */
    @ManyToMany(cascade = CascadeType.ALL, fetch = FetchType.EAGER)
    @JoinTable(
            name = "trainingsession_exercises",
            joinColumns = @JoinColumn(name = "training_id"),
            inverseJoinColumns = @JoinColumn(name = "exercise_id"))
    private Set<Exercise> exercises;
}

